### ISSUE TITLE
1.7.0 or later support?

### ISSUE THREAD

**Issue by andoruB** [Misterkid/More-Options#1]
Would it be possible to make this work with the newer versions of Cities Skylines? Tried putting the source files for the mod under the specified subfolder under my home folder (I'm using Linux) that's specified in C:S modding documentation, but it just gives me errors that it cannot open/read/parse the dll file.

**Comment by Quget** [comment]
Well the main features of this mod is now in the main game if I'm right :S 
What feature of this mod do you want to use ?

**Comment by andoruB** [comment]
> Well the main features of this mod is now in the main game if I'm right :S

If they are, then I have no idea where I could look for them.

> What feature of this mod do you want to use ?

I want to use the advanced graphics settings, like turning off bloom and fog and other stuff that make it hard to see stuff, and also to gain some FPS. To tell you honestly, I don't know what other features your mod has, since the mod page on Steam has been removed. I've previously played the 1.1.1c version of the game almost two years ago and it ran fine, then I started playing the game again, upgraded it, and found out that the FPS drops down every few minutes or so, making it harder to play the game.

**Comment by andoruB** [comment]
@Misterkid ?

**Comment by Quget** [comment]
I am not planning to work on this mod anymore, I'm too busy with other things at the moment.
You can look at the source code and make your own version if you like :)

**Comment by andoruB** [comment]
I don't want to make another version of the mod, I just want to know how to get it working in the game...
